# Generated by Django 2.2.1 on 2019-05-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuation', models.IntegerField(blank=True, verbose_name='Puntuación')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_list', to='comments.Entity', verbose_name='Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Comentario')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.Entity', verbose_name='Entidad')),
            ],
        ),
    ]
